class Settings {

  static var address = {
    "states": [
     {"value": "ALL", "name": "Estado - Todos"},
     {"value": "AC", "name": "Acre"},
     {"value": "AL", "name": "Alagoas"},
     {"value": "AP", "name": "Amapá"},
     {"value": "AM", "name": "Amazonas"},
     {"value": "BA", "name": "Bahia"},
     {"value": "CE", "name": "Ceará"},
     {"value": "DF", "name": "Distrito Federal"},
     {"value": "ES", "name": "Espírito Santo"},
     {"value": "GO", "name": "Goías"},
     {"value": "MA", "name": "Maranhão"},
     {"value": "MT", "name": "Mato Grosso"},
     {"value": "MS", "name": "Mato Grosso do Sul"},
     {"value": "MG", "name": "Minas Gerais"},
     {"value": "PA", "name": "Pará"},
     {"value": "PB", "name": "Paraíba"},
     {"value": "PR", "name": "Paraná"},
     {"value": "PE", "name": "Pernambuco"},
     {"value": "PI", "name": "Piauí"},
     {"value": "RJ", "name": "Rio de Janeiro"},
     {"value": "RN", "name": "Rio Grande do Norte"},
     {"value": "RS", "name": "Rio Grande do Sul"},
     {"value": "RO", "name": "Rondônia"},
     {"value": "RR", "name": "Roraíma"},
     {"value": "SC", "name": "Santa Catarina"},
     {"value": "SP", "name": "São Paulo"},
     {"value": "SE", "name": "Sergipe"},
     {"value": "TO", "name": "Tocantins"}
    ],
    "clinicType": [
      {"id": 1, "name": "Segmento - Todos"},
      {"id": 2, "name": "Odontologia"},
      {"id": 3, "name": "Cirurgia plástica"},
      {"id": 4, "name": "Estética geral"},
      {"id": 5, "name": "Ginecologista"},
      {"id": 6, "name": "Oftalmologia"},
      {"id": 7, "name": "Clinica geral"},
      {"id": 8, "name": "Hospital"},
      {"id": 9, "name": "Ortopedia"},
      {"id": 10, "name": "Exames & Diagnósticos"},
      {"id": 11, "name": "Farmácia"},
    ],
  };
}